//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int itemID { get; set; }
        public string itemName { get; set; }
        public int itemPrice { get; set; }
        public Nullable<int> resturantID { get; set; }
    
        public virtual resturant resturant { get; set; }
    }
}
