//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resturant
    {
        public resturant()
        {
            this.addresses = new HashSet<address>();
            this.items = new HashSet<item>();
        }
    
        public int resturantID { get; set; }
        public string resturantName { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<item> items { get; set; }
    }
}
